### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by NoobishSVK** [NoobishSVK/fm-dx-webserver#3]
We can use this issue to discuss the current tasks.

These tasks are currently planned:
- [x] Make AF list clickable 
- [x] Add RF+/IF+ (iQ/EMS) 
- [x] Add 3LAS support (Low-Latency audio stream)
- [ ] Pack the entire project into a single binary so node.js isn't needed
- [ ] Make screenshots possible with a button/keypress
- [ ] Add password auth
- [x] Improve auto frequency rounding on FM
- [ ] Modify frequency steps for AM and OIRT
- [x] Improve UI for mobile devices
- [x] Make RT copyable 
- [x] Refactor code 
- [x] Reset RDS (on R press)
- [x] Accessibility features (for visually impaired people)
- [x] Custom scrollbar (for the AF bar) 
- [ ] Web setup
- [x] Broadcast on all IPs by default  
- [ ] Add admin password for remote settings management
- [x] Add warning/info messages for xdrd authentication
- [x] Add a link to Discord in the settings modal

**Comment by andimik** [comment]
- defined band margins (FM, OIRT) resp. switching between bands
- tuning steps (100 kHz, 200 kHz)
- US/Europe switch
- export (or make streamable) RDS (with timestamp for RDSSpy) on different page or port
- decrease UI size for desktops
- don't place elements absolute but relative

**Comment by PE5PVB** [comment]
Use mousewheel to go freq up/down.

**Comment by NoobishSVK** [comment]
I am closing this task list due to making a new one using Trello - this task list is public and members are always welcome to give me the feedback on our Discord server. I will be slowly adding features requested by users here on GitHub as well. 
https://trello.com/b/OAKo7n0Q/fm-dx-webserver
